package com.java.oops.constructor;

public class DefaultConstructor
{
	// 1. Compiler is responsible to generate default constructor (but not JVM).

	// 2. If we're not writing any constructor then only compiler will generate default constructor i.e. if we're
	// writing at-least one constructor then compiler won't generate default constructor. Hence, every class in java can
	// contain constructor, it may be default constructor generated by compiler or customized constructor explicitly
	// provided by programmer but not both simultaneously.

	/** Prototype of default constructor **/

	// 1. It is always no-arg constructor.

	// 2. The access modifier of default constructor is exactly same as access modifier of class (this rule is
	// applicable only for public and default).

	// 3. It contains only 1 line i.e. 'super();'. It is a no-arg call to super class constructor.
	
	// Refer: Programmer_vs_Compiler_Code.PNG Note: Code highlighted in red is added by compiler. 
}
